---
title: "Wino Sem. letni"
output: html_notebook
---


```{r}

#Ladowanie pakietow

library(XLConnect)
library(dplyr)
library(VIM)
library(ggplot2)
library(questionr)
library(ca)


#Ladowanie i porzadkowanie danych

Arkusz <- loadWorkbook("ankiety_wino.xlsx")

Dane_wszystko <- readWorksheet(Arkusz, sheet=1)

Dane_wszystko <- Dane_wszystko [-c(1,9)]

Dane_wszystko <- Dane_wszystko [,c(5:7,1:4,8:11)]

#Lista hipotez i proponowane rozwiazania
# 1.	Czy osoba młoda zarabiająca bardzo dobrze jest bardziej skłonna pić wina czerwone wytrawne? (Korelacja pomiędzy zarobkami i wiekiem, a wytrawnością kupowanych win i rodzajem wina)
# 
# => 
# 
# 2.	Czy osoba pijąca mało jest w stanie zapłacić więcej za wino niż osoba, która pije dużo wina [badamy elastyczność cenową konsuemnta]
# 
# => Model regresji liniowej log / log -> Zbudować model, potem zweryfikować założenia wizualnie, a potem zweryfikować testami z ekonometrii (lm test – normalne reszty, test durbina Watsona,). Jeżeli zał nie spełnione to użycie odpornych estymatorów zmiennych standardowych (ROBUST standard errors) – pakiet sandwitch
# 
# 3.	Czy wzrost wytrawności (od słodkiego do wytrawnego) wpływa na cenę, którą osoba jest stanie wydać na ulubione wino?
# 
# => Spróbować dołączyć do modelu z 2 (zrobić wykres rozrzutu, który sprwadzi czy ilość wypitych win rośnie wraz z wytrawnością). Test vif (w pakiecie car). 
# 
# 4.	Czy wraz ze wzrostem spożytego wina wzrasta wytrwałość spożywanego wina. 
# 
# 
# 5.	Jeżeli ktoś sięga po wino słodkie to jest to wino białe lub różowe, a jeżeli wytrawne to wino czerwone.
# 
# => Testem Chi kwadrat. Analiza korespondencji (wizualizacja tabeli kontyngencji) 
# 
# 6.	Jaka jest wytrawność w grupach wiekowych 
# 
# => Test Chi kwadrat i miary korelacji (V-Cramera) 
# 
# 7.	Czy istnieje korelacja, że im osoba starsza tym więcej wina pije, bądź czy to młodzi dużo kupują 
# 
# => Zroibł Box ploty i zrobić test kruskala Wallisa (sprwadzić czy rozkłady są takie same) 
# 
# 
# 
# => Model regresji logistycznej (wyjaśniamy prawdopobieństwo tego czy ktoś wybiera jakąś kategorię).
# 
# Książka: Mikroekonometryczne metody badania preferencji konsumentów z wykorzystaniem programu R
# Regresja logistyczna wielomianowa ( mlogit lub mnlogit).


```

```{r}
#Imputacja danych 

Po_imputacji_k1 <- kNN(Dane_wszystko, k = 1)



#w przypadku zmiennych ciągłych robi ważone, w przypadku zmiennych jakościowych najcześciej wybierane. 
#Im więcej sąsiadów tym rozkład może być bardziej wysmukły. 



#TESTY DR. BERESEWICZA
plot(Dane_wszystko$Pyt.6, Dane_wszystko$Pyt.7)
abline(a=0,b=1, col='red')


Dane_wszystko <- Dane_wszystko %>% mutate(roznica = Pyt.7 - Pyt.6)
kruskal.test(roznica~Pyt.4.1, Dane_wszystko)
boxplot(roznica~Pyt.4.1, Dane_wszystko, ylim = c(-200,200))
model1 <- lm(roznica ~ factor(Pyt.4.1), Dane_wszystko)
summary(model1)


#Test t srednich 
# ANOVA dla wiecej srednich
# Test kruskala walisa, bo nieparametryczny ! 

```


```{r}

#Porzadkowanie poszczegolnych zmiennych 

aggr(Dane_wszystko) #funkcja do wyrysowania braków danych (w obiekcie zwraca też statystyki opisowe)


Kolor         <- Dane_wszystko %>% 
                  count(Pyt.1) %>%
                  mutate(procent=n/sum(n))

Musujace      <- Dane_wszystko %>% 
                 count(Pyt.2) %>%
                 mutate(procent=n/sum(n))

Wytrawnosc    <- Dane_wszystko %>% 
                 count(Pyt.3) %>%
                 mutate(procent=n/sum(n))

Plec          <- Dane_wszystko %>% 
                 count(Pyt.1.1) %>%
                 mutate(procent=Plec $n/sum(Plec $n))

Zamieszkanie  <- Dane_wszystko %>% 
                 count(Pyt.2.1) %>%
                 mutate(procent=n/sum(n))

Wiek          <- Dane_wszystko %>% 
                 count(Pyt.3.1) %>%
                 mutate(procent=n/sum(n))

Zarobki       <- Dane_wszystko %>% 
                 count(Pyt.4.1) %>%
                 mutate(procent=n/sum(n))

Sr_wydatki    <- summary(Dane_wszystko$Pyt.4)

Sr_spozycie   <- summary(Dane_wszystko$Pyt.5)

#Usuniecie NA z Pyt 6 i 7 i zmiana typu na num

Ulubione_wyd_dane <- Dane_wszystko$Pyt.6
Ulubione_wyd_dane$.[Ulubione_wyd_dane$. %in% c("NA")] <- NA
Ulubione_wyd_dane  <- Ulubione_wyd_dane [!is.na(Ulubione_wyd_dane)] 
Ulubione_wyd_dane <- as.numeric(as.character(Ulubione_wyd_dane))
Ulubione_wyd_summ <- summary(Ulubione_wyd_dane)


  
Ulubione_nad  <- summary(Dane_wszystko$Pyt.7)
  
hist(log(Dane_wszystko$Pyt.7), breaks = 'fd')

```


```{r}

#7.	Czy istnieje korelacja, że im osoba starsza tym więcej wina pije, bądź czy to młodzi dużo kupują 

  #sprawdzenie dla ilosci
  #Rozklad ilosci pitego wina - bardzo silna asymetria prawostronna, jednakze raczej 1 modalny
  ggplot(Po_imputacji_k1, aes(x = Pyt.5)) + 
  geom_density()

  #Rozklad ilosci po uzyciu ln - wyglada calkiem normalnie 
  ggplot(Po_imputacji_k1, aes(x = log(Pyt.5))) + 
  geom_density()
  
  #Histogram
  ggplot(Po_imputacji_k1, aes(x = Pyt.5)) + 
  geom_histogram(binwidth=10)
 
  #normalnosc - H0 o normalnosci odrzucona.
  shapiro.test(Po_imputacji_k1$Pyt.5)
  
  #Sprawdzenie dla wieku
  #Rozklad wieku, Bi modlany - druga moda w najstarszej grupie wiekowej 
  ggplot(Po_imputacji_k1, aes(x = Pyt.4.1)) + 
  geom_density()
  
   #Histogram
  hist(Po_imputacji_k1$Pyt.4.1)

  #normalnosc - H0 o normalnosci odrzucona.
  shapiro.test(Po_imputacji_k1$Pyt.4.1)
  
  
  boxplot(Pyt.5 ~ Pyt.4.1, data = Po_imputacji_k1)
  kruskal.test(Pyt.5~Pyt.4.1, Po_imputacji_k1)
  #Alternatywa: https://pl.wikipedia.org/wiki/Test_Wilcoxona_dla_par_obserwacji  [Podpytaj]
  
  


```





```{r}
#6.	Jaka jest wytrawność w grupach wiekowych - zaleznosc miedzy wytrawnoscia a wiekiem

#Stworzenie tabeli kontyngencji
tabela_wiek_wytrawnosc <- table(Po_imputacji_k1$Pyt.3,Po_imputacji_k1$Pyt.4.1)
#Zmiana tabeli kontyngencji w data frame
count_df <- transpose(as.data.frame.matrix(tabela_wiek_wytrawnosc))
#Test chi kwadrat dla nieprzeksztalconej tabeli kontyngencji - uwaga malo obserwacji w sporej czesci kateogrii
chisq.test(tabela_wiek_wytrawnosc)
#Test V-kramera - mozliwy blad ze wzgledu na mala ilosc obserwacji
cramer.v(count_df)



#Stwrzoenie data frame, w ktorym uwzgledniamy wina wytrawne i inne jako osobna kategorie 
wyt_nie_wyt_df <- count_df %>%
                  mutate(Wyt = V1,
                         Nie_wyt = V2 + V3 + V4) %>%
                  select(-starts_with('V'))

#Test Chi kwadrat dla przeksztalconej tabeli
chisq.test(wyt_nie_wyt_df)

#Test V kramera dla przeksztalconej tabeli
cramer.v(wyt_nie_wyt_df)


#Polaczenie grupy 4 i 5 (ze wzgledu na male ilosci nie wytrawnych w obu)

wyt_nie_wyt_df_2 <- wyt_nie_wyt_df %>%
                    rbind("4 i 5" = wyt_nie_wyt_df[4,] + wyt_nie_wyt_df[5,])

#Usuniecie 4 i 5 wiersza          
wyt_nie_wyt_df_2 <- wyt_nie_wyt_df_2[-c(4:5),]


#Test dla ostatecznie poprawionych i zlaczonych danych 
chisq.test(wyt_nie_wyt_df_2)

#Test V kramera dla przeksztalconej tabeli - ostatecznie
cramer.v(wyt_nie_wyt_df_2)

#Analiza korespondencji 
ca_anal <- ca(tabela_wiek_wytrawnosc)
print(ca_anal)
#Wizualizacja analizy korespondencji
plot(ca_anal)
plot(ca_anal, mass = TRUE, contrib = "absolute", map =
   "rowgreen", arrows = c(FALSE, TRUE))

```

```{r}
#5.	Jeżeli ktoś sięga po wino słodkie to jest to wino białe lub różowe, a jeżeli wytrawne to wino czerwone.

tabela_kolor_wytrawnosc <- table(Po_imputacji_k1$Pyt.3,Po_imputacji_k1$Pyt.1)

kolor_wyt_df <- transpose(as.data.frame.matrix(tabela_kolor_wytrawnosc))

#Test chi kwadrat dla nieprzeksztalconej tabeli kontyngencji - uwaga malo obserwacji w sporej czesci kateogrii
chisq.test(tabela_kolor_wytrawnosc)
#Test V-kramera - mozliwy blad ze wzgledu na mala ilosc obserwacji
cramer.v(kolor_wyt_df)

#Stworzenie kategori slodkie (caly czas bedzie wadzic rozowe)
kolor_wyt_df_2 <-   kolor_wyt_df %>%
                    mutate(Wyt = V1,
                           Pol_wyt = V2,
                           Slod = V3 + V4) %>%
                    select(-starts_with('V'))
#test chi i v kram dla tabeli ze zlaczonym slodkim
chisq.test(kolor_wyt_df_2)
cramer.v(kolor_wyt_df_2)

#Zlaczenie bialego i rozwego 

czerw_nieczerw <- kolor_wyt_df_2 %>%
                    rbind("nie_czerw" = kolor_wyt_df_2[1,] + kolor_wyt_df_2[3,])

czerw_nieczerw <- czerw_nieczerw[-c(1,3),]

#Ostateczne testy - podzial na czerwone i inne, dodatkowo wytrawn, pol wytrawne i slodkie 
chisq.test(czerw_nieczerw)
cramer.v(czerw_nieczerw)

#Podzial na czerwone i inne + na slodkie i wytrawne (polaczenie kategorii pol)
czerw_nieczerw_2 <- czerw_nieczerw %>%
                    mutate (Wytrawne = Wyt + Pol_wyt)
czerw_nieczerw_2 <- czerw_nieczerw_2[,-c(1,2)]

chisq.test(czerw_nieczerw_2)
cramer.v(czerw_nieczerw_2)

#Analiza krespondenci - pakiet ca

fit <- ca(tabela_kolor_wytrawnosc)
print(fit)
#narysowanei wykresow do analizy korespondencji! 
plot(fit)
plot(fit, mass = TRUE, contrib = "absolute", map =
   "rowgreen", arrows = c(FALSE, TRUE))

```

```{r}




```

